---
title: "Referral Data Review"
author: "Enterprise Analytics"
date: "`r paste0('Last Updated: ', format(Sys.time(), '%d %B, %Y')) `"
keywords: 
  - Mebane Cancer Center
  - Referrals
output:
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
knitr::opts_chunk$set(fig.align = 'center', fig.width=12, out.width="100%")
library(tidyverse)
library(eastyle)
library(sf)
library(gt)

# library(eatools)
# To Turn off Scientific Notation Use this.
options(scipen = 999)

load(file = here::here("data-raw", "ref_clean.rda"))
load(file = here::here("data-raw", "ref_Output.rda"))
load(file = here::here("data-raw", "MebCC_Providers.rda"))
load(file = here::here("data-raw", "dpts_Output.rda"))
load(file = here::here("data-raw", "pats_geo.rda"))

NCplaces <- tigris::places(state = "NC")

ala_cities <-
  NCplaces %>% 
  filter(NAME %in%  c("Burlington", "Graham", "Mebane"))

NCtracts <- tigris::tracts(state = "NC", county = c("Alamance", "Guilford", "Orange", "Caswell"))  

```


```{r}

MebPats <- ref_Output %>% 
  filter(ReferredToDepartmentID %in% c('10023392304')) %>% 
  left_join(., pats_geo, by = c("PatientID")) %>% 
  mutate(GeoComp = ifelse(X == 0, "Not Geo", "Patient Geo")) %>% 
  filter(is.na(DenyReasonDSC),
         !ReferralStatusDSC %in% c('Denied', 'Incomplete', 'Canceled'),
         !ReferralTypeDSC %in% c('Auth/Cert'),
         !SchedulingStatusDSC %in% c('Do Not Schedule', 'Patient Refusal', 'Unable to Contact',
                                     'Called 1x', 'Called 2x', 'Called 3x',
                                     'Appointment Canceled'))


# MebPats %>% 
#   distinct(PatientID, GeoComp) %>% 
#   count(GeoComp) %>% 
#   mutate(Perc = n/sum(n))


ARMCPats <- ref_Output %>% 
  filter(ReferredToDepartmentID %in% c('10023393304', '10010380304')) %>% #ARMC
  left_join(., pats_geo, by = c("PatientID")) %>% 
  mutate(GeoComp = ifelse(X == 0, "Not Geo", "Patient Geo")) %>% 
  filter(is.na(DenyReasonDSC),
         !ReferralStatusDSC %in% c('Denied', 'Incomplete', 'Canceled'),
         !ReferralTypeDSC %in% c('Auth/Cert'),
         !SchedulingStatusDSC %in% c('Do Not Schedule', 'Patient Refusal', 'Unable to Contact',
                                     'Called 1x', 'Called 2x', 'Called 3x',
                                     'Appointment Canceled'))

```


# Patient Locations {.tabset .tabset-pills}

## Referred to Mebane

```{r, fig.height=8, out.width="100%"}
DistcPats <-
  MebPats %>% 
  distinct(PatientID, X, Y, RE = SixRaceEthnicity, SexDSC, GeoComp, BirthDTS) %>% 
  filter(!X == 0) %>% 
  st_as_sf(coords = c("X", "Y"),crs = 4269) %>% 
  st_transform(crs = 4269) %>% 
  cbind(., st_coordinates(.))

OncPats <- DistcPats %>% 
  st_transform(crs = 4269) %>% 
  mutate(WithNC = lengths(st_intersects(., NCtracts))) %>% 
  filter(WithNC == 1) %>% 
  group_by(RE) %>% 
  mutate(Count = n()) %>% 
  filter(Count >= 10) %>% 
  mutate(RE = factor(RE),
         RE = fct_reorder(RE, Count))


OncPats %>% 
  ggplot() +
  geom_sf(data = NCtracts, color="grey", fill="white") +  
  geom_sf(data = ala_cities, color="grey", fill="grey50", alpha=0.6) +  

  geom_point(aes(x=X, y=Y), size = 0.8, alpha=0.6) + #, color = "black"
  stat_density_2d(data = OncPats, aes(X,Y, fill = (..level..)), geom = "polygon", alpha=0.25) +
  

  scale_x_continuous(breaks = NULL) +
  scale_y_continuous(breaks = NULL) +
  labs(title = "Oncology Patients Referred to Mebance Cancer Center",
       subtitle= "For patients with referral from 2019 - Jan 2021",
       y = NULL, x=NULL, color=NULL)+
  theme(plot.title = element_text(20),
        plot.subtitle = element_text(size= 16),
        plot.caption = element_text(size= 16),
        axis.text = element_blank(),
        strip.text = element_text(face = "bold", size = 12),
        legend.position = "none")+
  # guides(colour = guide_legend(override.aes = list(size=5))) +
  facet_wrap(~RE, ncol = 2)



```



```{r}
DistcPats %>% 
  st_drop_geometry() %>% 
  mutate(Age = as.numeric(Sys.Date()- as.Date(BirthDTS))/365.25) %>% 
  filter(Age < 110) %>% 
  group_by(RE) %>% 
  summarise(AvgAge = median(Age, na.rm=T),
            Count = n()) %>% 
  ungroup() %>% 
  mutate(Per = Count/sum(Count)) %>% 
  rename(RaceEthnicity = RE) %>%
  arrange(desc(Count)) %>% 
  gt() %>% 
  fmt_percent(columns = vars(Per)) %>% 
  fmt_number(columns = 2) %>% 
  fmt_number(columns = 3, decimals = 0)
```

## Referred to ARMC

```{r, fig.height=8, out.width="100%"}
DistcPats <-
  ARMCPats %>% 
  distinct(PatientID, X, Y, RE = SixRaceEthnicity, SexDSC, GeoComp, BirthDTS) %>% 
  filter(!X == 0) %>% 
  st_as_sf(coords = c("X", "Y"),crs = 4269) %>% 
  st_transform(crs = 4269) %>% 
  cbind(., st_coordinates(.))


OncPats <- DistcPats %>% 
  st_transform(crs = 4269) %>% 
  mutate(WithNC = lengths(st_intersects(., NCtracts))) %>% 
  filter(WithNC == 1) %>% 
  group_by(RE) %>% 
  mutate(Count = n()) %>% 
  # filter(Count >= 10) %>% 
  mutate(RE = factor(RE),
         RE = fct_reorder(RE, Count))


OncPats %>% 
  ggplot() +
  geom_sf(data = NCtracts, color="grey", fill="white") +  
  geom_sf(data = ala_cities, color="grey", fill="grey50", alpha=0.6) +  

  geom_point(aes(x=X, y=Y), size = 0.8, alpha=0.6) + #, color = "black"
  stat_density_2d(data = OncPats, aes(X,Y, fill = (..level..)), geom = "polygon", alpha=0.25) +
  

  scale_x_continuous(breaks = NULL) +
  scale_y_continuous(breaks = NULL) +
  labs(title = "Oncology Patients Referred to ARMC",
       subtitle= "For patients with referral from 2019 - Jan 2021",
       y = NULL, x=NULL, color=NULL)+
  theme(plot.title = element_text(20),
        plot.subtitle = element_text(size= 16),
        plot.caption = element_text(size= 16),
        axis.text = element_blank(),
        strip.text = element_text(face = "bold", size = 12),
        legend.position = "none")+
  # guides(colour = guide_legend(override.aes = list(size=5))) +
  facet_wrap(~RE, ncol = 3)



```



```{r}
DistcPats %>% 
  st_drop_geometry() %>% 
  mutate(Age = as.numeric(Sys.Date()- as.Date(BirthDTS))/365.25) %>% 
  filter(Age < 110) %>% 
  group_by(RE) %>% 
  summarise(AvgAge = median(Age, na.rm=T),
            Count = n()) %>% 
  ungroup() %>% 
  mutate(Per = Count/sum(Count)) %>% 
  rename(RaceEthnicity = RE) %>%
  arrange(desc(Count)) %>% 
  gt() %>% 
  fmt_percent(columns = vars(Per)) %>% 
  fmt_number(columns = 2) %>% 
  fmt_number(columns = 3, decimals = 0)
```

